weba:
  image: gm7y8/ubuntu
  expose:
    - 80

webb:
  image: gm7y8/ubuntu
  expose:
    - 80

webc:
  image: gm7y8/ubuntu
  expose:
    - 80

haproxy:
  image: my-haproxy
  links:
   - weba
   - webb
   - webc
  ports:
   - "80:80"
   - "70:70"

  expose:
   - "80"
   - "70"
~        
